import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
source code is available in the plugin repository
*/`;

const watch = process.argv.includes("--watch");

const ctx = await esbuild.context({

  entryPoints: ["src/main.ts"],

  bundle: true,

  outfile: "main.js",

  format: "cjs",

  platform: "node",

  target: "es2020",

  banner: {
    js: banner
  },

  external: [
    "obsidian",
    "electron",

    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",

    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",

    ...builtinModules
  ],

  treeShaking: true,

  sourcemap: watch ? "inline" : false,

  minify: !watch,

  logLevel: "info"

});

if (watch) {

  await ctx.watch();

} else {

  await ctx.rebuild();

  process.exit(0);

}