// src/features/daily_review/i18n/en.ts

export const enTexts = {
  // --- コメント（複数行） ---
  'daily-review-comment': [
    'The following summary was generated by an LLM based on today’s activities.',
    'Please check incorrect lines and add review comments if necessary.',
    'These review comments will be used in the subsequent KPT analysis.',
  ],

  'review-point-action-comment': [
    '[XMind Review Procedure]',
    '1. Copy all text under the "Input" section.',
    '2. Paste it into XMind and edit it (adjust structure, granularity, and wording).',
    '3. Paste the edited content under the "Output" section.',
    '4. The "Output" section will be recorded as the summary of the review.',
  ],

  'xmind-input-heading': 'Input (for XMind)',
  'xmind-output-heading': 'Output（XMind editing result）',

  'daily-review-unregistered-guide': [
    '※ Some unregistered tags were detected.',
    '-> Please use the command "**Register and Merge Tags into Alias Dictionary**" to normalize them.',
  ],
} as const;
