import { parseTabbedXMindOutline } from "../XMindOutline";

describe("parseTabbedXMindOutline", () => {
	test("parses tab-indented topics and strips comments", () => {
		const result = parseTabbedXMindOutline([
			"<!--",
			"usage",
			"-->",
			"",
			"KPT",
			"\tKeep",
			"\tProblem",
			"\tTry",
		].join("\n"));

		expect(result).toEqual([
			{
				title: "KPT",
				children: [
					{ title: "Keep", children: [] },
					{ title: "Problem", children: [] },
					{ title: "Try", children: [] },
				],
			},
		]);
	});

	test("drops top-level Fact because it is generated by ptune-task", () => {
		const result = parseTabbedXMindOutline([
			"Fact",
			"\tshould not be used",
			"KPT",
		].join("\n"));

		expect(result).toEqual([{ title: "KPT", children: [] }]);
	});
});
